### PR TITLE
Accha

### PR DESCRIPTION
**Pull request by IntegerBytes**
Copyright law in the U.S. is governed by federal statute, namely the Copyright Act of 1976. The Copyright Act prevents the unauthorized copying of a work of authorship. However, only the copying of the work is prohibited--anyone may copy the ideas contained within a work. For example, a copyright could cover a written description of a machine, but the actual machine itself is not covered. Thus, no one could copy the written description, while anyone could use the description to build the described machine.

Copyrights can be registered in the Copyright Office in the Library of Congress, but newly created works do not need to be registered. In fact, it is no longer necessary to even place a copyright notice on a work for it to be protected by copyright law. However, the Copyright Act does provide additional benefits to those who register with the Copyright Office. Consequently, copyright registration and the use of a copyright notice is recommended.

The discussion of copyright law is divided into the following parts:

Obtaining Copyright Protection for a Work;
Works Unprotected by Copyright Law;
Scope of Protection Under Copyright Law;
Fair Use and Other Limitations on Copyright Protection;
Copyright Formalities: Notice and Registration;
Duration of Copyright Protection;
Ownership of Copyrights;
Transfers and Licensing of Copyrights;
Database Protection under Copyright Law; and
Mask Works.

Kindly Give me credits Else Get DMCA + According to USA Rule circular 92
 If you dont give me credits You Will be Charged So Get Ready for charge or Give me Credits

@Hobby-Dev-0 @LEGEND-OS

### CODE REVIEW

**Comment by Hobby-Dev-0** [comment]
Okay, Let me contact to @LEGEND-OS 

Heya @LEGEND-OS Listen Kindly Give Him Credits He only Helped me in Addons If You Dont Give Credits He Will DMCA Your Repo And then You Cant make repo public in anyway So Kindly Give Credits or Remove That Lines of Codes I meant remove Addons Support

**Comment by Hobby-Dev-0** [comment]
@LEGEND-OS Again invite me in Your Repo

**Comment by IntegerBytes** [comment]
If I wont Find my credits A DMCA will be sent to you by Github

**Comment by IntegerBytes** [comment]
Your Repo Will be Disabled Within in 15 days from tomorrow count 15 days 🎉

**Comment by LEGEND-OS** [comment]
@Hobby-Dev-0 telegram par aa sakte ho

**Comment by Hobby-Dev-0** [comment]
@LEGEND-OS Bro Nahi Aa skta

**Comment by LEGEND-OS** [comment]
@Hobby-Dev-0 why i need to give credit

**Comment by Hobby-Dev-0** [comment]
@Hobby-Dev-0 To him because he is the real Owner Of that code Addons Nor me or you

**Comment by LEGEND-OS** [comment]
accha addons ka

**Comment by Hobby-Dev-0** [comment]
@LEGEND-OS Invite me on Repo

**Comment by LEGEND-OS** [comment]
Ok

**Comment by Hobby-Dev-0** [comment]
Han Addons Ka

**Comment by LEGEND-OS** [comment]
dn

**Comment by LEGEND-OS** [comment]
@Hobby-Dev-0 chekc

**Comment by LEGEND-OS** [comment]
@IntegerBytes username on telegram

**Comment by IntegerBytes** [comment]
@LEGEND-OS Why you removed my credits

**Comment by Hobby-Dev-0** [comment]
@LEGEND-OS Why Removed Me Again😒😑

**Comment by LEGEND-OS** [comment]
ufff

**Comment by LEGEND-OS** [comment]
karta hu add

**Comment by LEGEND-OS** [comment]
@Hobby-Dev-0 main telegram leave kar diya hu

**Pull request merged**
